from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]


REQUIRED_ROOT_LINKS = {
    "docs/README.md",
    "skills/README.md",
    "docs/getting-started.md",
    "docs/npu-ai-coding-standard-workflow.md",
}


def markdown_links(path: Path) -> list[str]:
    return re.findall(r"(?<!!)\[[^]]+\]\(([^)]+)\)", path.read_text(encoding="utf-8"))


def local_target(path: Path, link: str) -> Path | None:
    if "://" in link or link.startswith("#"):
        return None
    clean = link.split("#", 1)[0].split("?", 1)[0]
    return (path.parent / clean).resolve()


def test_root_readmes_link_required_current_entry_points():
    for name in ("README.md", "README_zh.md"):
        text = (ROOT / name).read_text(encoding="utf-8")
        for link in REQUIRED_ROOT_LINKS:
            assert f"]({link})" in text, (name, link)


def test_root_readmes_keep_aligned_major_section_order():
    english = ["Choose your path", "Five-minute start", "How the pieces fit together", "Browse capabilities", "Documentation", "Repository map", "Contribution and support boundaries"]
    chinese = ["选择任务入口", "五分钟开始", "各部分如何协作", "浏览能力", "文档", "仓库地图", "贡献与支持边界"]
    for name, headings in (("README.md", english), ("README_zh.md", chinese)):
        text = (ROOT / name).read_text(encoding="utf-8")
        positions = [text.index(f"## {heading}") for heading in headings]
        assert positions == sorted(positions)


def test_docs_hub_links_current_guides_and_labels_design_history():
    hub = (ROOT / "docs/README.md").read_text(encoding="utf-8")
    required = [
        "getting-started.md", "npu-ai-coding-standard-workflow.md",
        "../skills/README.md", "architecture/repository-map.md",
        "architecture/skill-map.md", "maintainers/adding-or-changing-a-skill.md",
        "../scripts/README.md", "pr12/PLAN.md",
    ]
    for link in required:
        assert f"]({link})" in hub
    assert "设计记录" in hub
    assert "不是默认工作流入口" in hub


def test_curated_navigation_local_links_resolve():
    files = [
        ROOT / "README.md", ROOT / "README_zh.md", ROOT / "docs/README.md",
        ROOT / "docs/getting-started.md", ROOT / "docs/architecture/repository-map.md",
        ROOT / "docs/maintainers/adding-or-changing-a-skill.md",
    ]
    for path in files:
        for link in markdown_links(path):
            target = local_target(path, link)
            if target is not None:
                assert ROOT == target or ROOT in target.parents
                assert target.exists(), (path.relative_to(ROOT), link)


def test_generated_docs_are_not_presented_as_hand_edited():
    guide = (ROOT / "docs/maintainers/adding-or-changing-a-skill.md").read_text(encoding="utf-8")
    assert "不得手工编辑" in guide
    for path in (ROOT / "skills/README.md", ROOT / "docs/architecture/skill-map.md"):
        assert path.read_text(encoding="utf-8").startswith(
            "<!-- Generated by scripts/render_skill_docs.py. Do not edit manually. -->"
        )
