from copy import deepcopy
import importlib.util
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts/render_skill_docs.py"
SPEC = importlib.util.spec_from_file_location("render_skill_docs", SCRIPT)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)


def catalog():
    return json.loads((ROOT / "skills/catalog.json").read_text(encoding="utf-8"))


def test_generated_outputs_are_deterministic_and_current():
    value = catalog()
    first = (MODULE.render_skills_readme(value), MODULE.render_skill_map(value))
    shuffled = deepcopy(value)
    shuffled["skills"].reverse()
    second = (MODULE.render_skills_readme(shuffled), MODULE.render_skill_map(shuffled))
    assert first == second
    assert (ROOT / "skills/README.md").read_text(encoding="utf-8") == first[0]
    assert (ROOT / "docs/architecture/skill-map.md").read_text(encoding="utf-8") == first[1]


def test_check_detects_drift_without_rewriting(monkeypatch, tmp_path):
    target = tmp_path / "generated.md"
    target.write_text("stale\n", encoding="utf-8")
    monkeypatch.setattr(MODULE, "load_catalog", lambda: catalog())
    monkeypatch.setattr(MODULE, "OUTPUTS", {target: lambda value: "expected\n"})
    assert MODULE.main(["--check"]) == 1
    assert target.read_text(encoding="utf-8") == "stale\n"


def test_role_view_contains_each_canonical_skill_exactly_once():
    value = catalog()
    role_section = MODULE.render_skills_readme(value).split("## By role", 1)[1].split("## By domain", 1)[0]
    for skill in value["skills"]:
        assert role_section.count(f"`{skill['id']}`") == 1


def test_domain_view_contains_every_public_skill_and_separates_internal():
    value = catalog()
    text = MODULE.render_skills_readme(value)
    domain_section = text.split("## By domain", 1)[1].split("## Public vs internal", 1)[0]
    for skill in value["skills"]:
        count = domain_section.count(f"`{skill['id']}`")
        assert count == (1 if skill["visibility"] == "public" else 0)
    internal = next(skill for skill in value["skills"] if skill["visibility"] == "internal")
    assert internal["presentation"]["featured"] is False
    assert "Internal / explicit-only" in text


def test_generated_skill_links_resolve_and_match_catalog():
    value = catalog()
    expected = {skill["directory"] for skill in value["skills"]}
    for path in (ROOT / "skills/README.md", ROOT / "docs/architecture/skill-map.md"):
        text = path.read_text(encoding="utf-8")
        assert text.startswith("<!-- Generated by scripts/render_skill_docs.py. Do not edit manually. -->")
        links = re.findall(r"\]\(([^)]+/SKILL\.md)\)", text)
        resolved = {(path.parent / link).resolve() for link in links}
        assert all(target.is_file() and ROOT in target.parents for target in resolved)
        directories = {target.parent.name for target in resolved}
        assert directories == expected
