#!/usr/bin/env python3
"""Render deterministic human skill views from skills/catalog.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "skills" / "catalog.json"
HEADER = "<!-- Generated by scripts/render_skill_docs.py. Do not edit manually. -->\n"
ROLE_ORDER = [
    ("orchestration", "Orchestration"),
    ("execution", "Execution"),
    ("analysis-and-diagnosis", "Analysis and diagnosis"),
    ("planning-and-knowledge", "Planning and knowledge"),
    ("development-and-review", "Development and review"),
    ("gates-and-support", "Gates and support"),
]
DOMAIN_ORDER = [
    "lifecycle", "performance", "evaluation", "accuracy", "profiling",
    "reliability", "build", "capacity", "knowledge", "development",
    "reporting", "remote-execution",
]


def load_catalog(path: Path = CATALOG) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def ordered_skills(catalog: dict) -> list[dict]:
    return sorted(catalog["skills"], key=lambda skill: skill["id"])


def link(skill: dict, prefix: str) -> str:
    return f"[{skill['presentation']['display_name']}]({prefix}{skill['directory']}/SKILL.md)"


def bullets(values: list[str]) -> str:
    return "; ".join(values)


def render_skills_readme(catalog: dict) -> str:
    skills = ordered_skills(catalog)
    public = [skill for skill in skills if skill["visibility"] == "public"]
    internal = [skill for skill in skills if skill["visibility"] == "internal"]
    lines = [HEADER.rstrip(), "", "# Skill Capability Index", "",
             "Use this generated index to choose a canonical workflow skill. Skill directories stay flat and installable; role and domain are logical catalog views.", "",
             "## How to choose a skill", "",
             "Start with the narrowest outcome that matches the request. Use lifecycle for run state, SOTA for open-ended optimization, mixed eval for performance plus accuracy, and specialist runners or analyzers for bounded work.", "",
             "## Featured primary entries", ""]
    for skill in public:
        if skill["presentation"]["featured"]:
            lines.append(f"- {link(skill, './')} — {skill['presentation']['summary']} (`{skill['id']}`)")
    lines += ["", "## By role", ""]
    for role, title in ROLE_ORDER:
        lines += [f"### {title}", ""]
        for skill in skills:
            if skill["presentation"]["role_group"] == role:
                marker = " — **Internal / explicit-only**" if skill["visibility"] == "internal" else ""
                lines.append(f"- {link(skill, './')} (`{skill['id']}`){marker}")
        lines.append("")
    lines += ["## By domain", ""]
    for domain in DOMAIN_ORDER:
        members = [skill for skill in public if skill["presentation"]["domain"] == domain]
        if members:
            lines += [f"### {domain.replace('-', ' ').title()}", ""]
            lines.extend(f"- {link(skill, './')} (`{skill['id']}`)" for skill in members)
            lines.append("")
    lines += ["## Public vs internal", "",
              f"- **Public:** {len(public)} skills with direct user outcomes.",
              f"- **Internal / explicit-only:** {len(internal)} skill. It may be explicitly invoked or delegated, but is not an implicit primary route.", ""]
    for skill in internal:
        lines.append(f"- {link(skill, './')} (`{skill['id']}`) — {skill['presentation']['summary']}")
    lines += ["", "## Skill cards", ""]
    for skill in skills:
        p = skill["presentation"]
        lines += [f"### {p['display_name']}", "", f"Canonical ID: `{skill['id']}`  ",
                  f"Role: `{p['role_group']}` · Domain: `{p['domain']}` · Exposure: `{p['exposure']}`  ",
                  f"{p['summary']}", "", f"**Use when:** {bullets(skill['primary_intents'])}.", "",
                  f"**Do not use when:** {bullets(skill['negative_intents'])}.", "",
                  f"**Outputs:** {bullets(p['outputs'])}.", "", f"Read {link(skill, './')}.", ""]
    lines += ["## Compatibility note", "",
              "All canonical IDs and flat directory paths are stable. xLLM on Ascend is the complete primary path. vLLM-Ascend and SGLang references are limited to the adapter or artifact scopes declared in the catalog.", ""]
    return "\n".join(lines)


def render_skill_map(catalog: dict) -> str:
    skills = ordered_skills(catalog)
    public = [skill for skill in skills if skill["visibility"] == "public"]
    internal = [skill for skill in skills if skill["visibility"] == "internal"]
    lines = [HEADER.rstrip(), "", "# Skill Architecture Map", "",
             "This detailed view is generated from `skills/catalog.json`. Presentation metadata explains human navigation; routing fields remain the skill ownership contract.", "",
             "## Counts", "", f"- Public: {len(public)}", f"- Internal / explicit-only: {len(internal)}", f"- Total canonical skills: {len(skills)}", "",
             "## Role and domain matrix", "", "| Canonical ID | Display name | Role | Domain | Exposure |", "|---|---|---|---|---|"]
    for skill in skills:
        p = skill["presentation"]
        lines.append(f"| `{skill['id']}` | {link(skill, '../../skills/')} | `{p['role_group']}` | `{p['domain']}` | `{p['exposure']}` |")
    lines += ["", "## Dependency graph", "", "Dependencies are catalog-declared delegation edges between canonical skills.", "", "```mermaid", "flowchart TD"]
    keys = {skill["id"]: f"s{index:02d}" for index, skill in enumerate(skills)}
    for skill in skills:
        lines.append(f"  {keys[skill['id']]}[\"{skill['id']}\"]")
    for skill in skills:
        for dependency in sorted(skill["dependencies"]):
            lines.append(f"  {keys[skill['id']]} --> {keys[dependency]}")
    lines += ["```", "", "## Framework and backend scope", "", "| Canonical ID | Framework scope | Backend scope |", "|---|---|---|"]
    for skill in skills:
        lines.append(f"| `{skill['id']}` | {bullets(skill['framework_scope'])} | {bullets(skill['backend_scope'])} |")
    lines += ["", "## Public skill details", ""]
    for skill in public:
        p = skill["presentation"]
        lines += [f"### {p['display_name']} (`{skill['id']}`)", "", p["summary"], "",
                  f"- **Use when:** {bullets(skill['primary_intents'])}.",
                  f"- **Do not use when:** {bullets(skill['negative_intents'])}.",
                  f"- **Outputs:** {bullets(p['outputs'])}.",
                  f"- **Skill:** {link(skill, '../../skills/')}", ""]
    lines += ["## Internal / explicit-only", ""]
    for skill in internal:
        p = skill["presentation"]
        lines += [f"### {p['display_name']} (`{skill['id']}`)", "", p["summary"], "",
                  "This capability is not eligible for implicit primary routing.", "",
                  f"- **Outputs:** {bullets(p['outputs'])}.",
                  f"- **Skill:** {link(skill, '../../skills/')}", ""]
    lines += ["## Support boundary", "",
              "**Supported:** xLLM on Ascend is the complete primary workflow.  ",
              "**Experimental adapter / artifact analysis only:** vLLM-Ascend and SGLang are limited to the exact catalog scopes shown above.  ",
              "**Internal / explicit-only:** internal skills do not participate in implicit primary routing.", ""]
    return "\n".join(lines)


OUTPUTS = {
    ROOT / "skills" / "README.md": render_skills_readme,
    ROOT / "docs" / "architecture" / "skill-map.md": render_skill_map,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail on drift without rewriting files")
    args = parser.parse_args(argv)
    catalog = load_catalog()
    drift: list[str] = []
    for path, renderer in OUTPUTS.items():
        expected = renderer(catalog)
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                try:
                    label = path.relative_to(ROOT)
                except ValueError:
                    label = path
                drift.append(str(label))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if drift:
        print("generated skill documentation is stale: " + ", ".join(drift), file=sys.stderr)
        return 1
    if not args.check:
        print("rendered: " + ", ".join(str(path.relative_to(ROOT)) for path in OUTPUTS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
