#!/usr/bin/env python3
"""Render deterministic human skill views from skills/catalog.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "skills" / "catalog.json"
HEADER = "<!-- Generated by scripts/render_skill_docs.py. Do not edit manually. -->\n"
ROLE_ORDER = [
    ("orchestration", "编排器"),
    ("execution", "执行器"),
    ("analysis-and-diagnosis", "分析与诊断"),
    ("planning-and-knowledge", "规划与知识"),
    ("development-and-review", "开发与审查"),
    ("gates-and-support", "门禁与支持工具"),
]
DOMAIN_ORDER = [
    "lifecycle", "performance", "evaluation", "accuracy", "profiling",
    "reliability", "build", "capacity", "knowledge", "development",
    "reporting", "remote-execution",
]


def load_catalog(path: Path = CATALOG) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def ordered_skills(catalog: dict) -> list[dict]:
    return sorted(catalog["skills"], key=lambda skill: skill["id"])


def link(skill: dict, prefix: str) -> str:
    return f"[{skill['presentation']['display_name']}]({prefix}{skill['directory']}/SKILL.md)"


def bullets(values: list[str]) -> str:
    return "; ".join(values)


def render_skills_readme(catalog: dict) -> str:
    skills = ordered_skills(catalog)
    public = [skill for skill in skills if skill["visibility"] == "public"]
    internal = [skill for skill in skills if skill["visibility"] == "internal"]
    lines = [HEADER.rstrip(), "", "# Skill 能力索引", "",
             "使用此生成索引选择 canonical workflow skill。Skill 目录保持扁平且可安装；角色与领域只是 catalog 提供的逻辑视图。", "",
             "## 如何选择 Skill", "",
             "从能够完整覆盖目标的最窄入口开始：run 状态使用 lifecycle，开放式优化使用 SOTA，性能与精度混合评测使用 eval，边界明确的单项任务使用专项执行器或分析器。", "",
             "## 推荐主入口", ""]
    for skill in public:
        if skill["presentation"]["featured"]:
            lines.append(f"- {link(skill, './')} — {skill['presentation']['summary_zh']}（`{skill['id']}`）")
    lines += ["", "## 按角色浏览", ""]
    for role, title in ROLE_ORDER:
        lines += [f"### {title}", ""]
        for skill in skills:
            if skill["presentation"]["role_group"] == role:
                marker = " — **内部 / 仅显式调用**" if skill["visibility"] == "internal" else ""
                lines.append(f"- {link(skill, './')} (`{skill['id']}`){marker}")
        lines.append("")
    lines += ["## 按领域浏览", ""]
    for domain in DOMAIN_ORDER:
        members = [skill for skill in public if skill["presentation"]["domain"] == domain]
        if members:
            lines += [f"### `{domain}`", ""]
            lines.extend(f"- {link(skill, './')} (`{skill['id']}`)" for skill in members)
            lines.append("")
    lines += ["## 公开与内部能力", "",
              f"- **公开：** {len(public)} 个具有直接用户目标的 skills。",
              f"- **内部 / 仅显式调用：** {len(internal)} 个 skill。它可以被显式调用或委托，但不能成为隐式主路由。", ""]
    for skill in internal:
        lines.append(f"- {link(skill, './')} (`{skill['id']}`) — {skill['presentation']['summary']}")
    lines += ["", "## Skill 卡片", ""]
    for skill in skills:
        p = skill["presentation"]
        lines += [f"### {p['display_name_zh']}（{p['display_name']}）", "", f"Canonical ID：`{skill['id']}`",
                  f"角色：`{p['role_group']}` · 领域：`{p['domain']}` · 暴露方式：`{p['exposure']}`",
                  f"{p['summary_zh']}", "", f"**适用场景：** {bullets(skill['primary_intents'])}。", "",
                  f"**不适用场景：** {bullets(skill['negative_intents'])}。", "",
                  f"**输出：** {bullets(p['outputs'])}。", "", f"查看 {link(skill, './')}。", ""]
    lines += ["## 兼容性说明", "",
              "所有 canonical ID 与扁平目录路径保持稳定。xLLM on Ascend 是完整主路径；vLLM-Ascend 与 SGLang 仅限 catalog 明确声明的 adapter 或 artifact scope。", ""]
    return "\n".join(lines)


def render_skill_map(catalog: dict) -> str:
    skills = ordered_skills(catalog)
    public = [skill for skill in skills if skill["visibility"] == "public"]
    internal = [skill for skill in skills if skill["visibility"] == "internal"]
    lines = [HEADER.rstrip(), "", "# Skill 架构地图", "",
             "此详细视图由 `skills/catalog.json` 生成。Presentation metadata 用于人类导航；routing 字段仍是 skill ownership 合约。", "",
             "## 数量", "", f"- 公开：{len(public)}", f"- 内部 / 仅显式调用：{len(internal)}", f"- Canonical skills 总数：{len(skills)}", "",
             "## 角色与领域矩阵", "", "| Canonical ID | 显示名称 | 角色 | 领域 | 暴露方式 |", "|---|---|---|---|---|"]
    for skill in skills:
        p = skill["presentation"]
        lines.append(f"| `{skill['id']}` | {link(skill, '../../skills/')} | `{p['role_group']}` | `{p['domain']}` | `{p['exposure']}` |")
    lines += ["", "## 依赖关系图", "", "依赖是 catalog 声明的 canonical skill 委托边。", "", "```mermaid", "flowchart TD"]
    keys = {skill["id"]: f"s{index:02d}" for index, skill in enumerate(skills)}
    for skill in skills:
        lines.append(f"  {keys[skill['id']]}[\"{skill['id']}\"]")
    for skill in skills:
        for dependency in sorted(skill["dependencies"]):
            lines.append(f"  {keys[skill['id']]} --> {keys[dependency]}")
    lines += ["```", "", "## Framework 与 backend scope", "", "| Canonical ID | Framework scope | Backend scope |", "|---|---|---|"]
    for skill in skills:
        lines.append(f"| `{skill['id']}` | {bullets(skill['framework_scope'])} | {bullets(skill['backend_scope'])} |")
    lines += ["", "## 公开 Skill 详情", ""]
    for skill in public:
        p = skill["presentation"]
        lines += [f"### {p['display_name_zh']}（{p['display_name']}，`{skill['id']}`）", "", p["summary_zh"], "",
                  f"- **适用场景：** {bullets(skill['primary_intents'])}。",
                  f"- **不适用场景：** {bullets(skill['negative_intents'])}。",
                  f"- **输出：** {bullets(p['outputs'])}。",
                  f"- **Skill：** {link(skill, '../../skills/')}", ""]
    lines += ["## 内部 / 仅显式调用", ""]
    for skill in internal:
        p = skill["presentation"]
        lines += [f"### {p['display_name_zh']}（{p['display_name']}，`{skill['id']}`）", "", p["summary_zh"], "",
                  "该能力不能参与隐式主路由。", "",
                  f"- **输出：** {bullets(p['outputs'])}。",
                  f"- **Skill：** {link(skill, '../../skills/')}", ""]
    lines += ["## 支持边界", "",
              "**完整支持：** xLLM on Ascend 是完整主工作流。",
              "**实验性 adapter / 仅 artifact 分析：** vLLM-Ascend 与 SGLang 仅限上表列出的 catalog scope。",
              "**内部 / 仅显式调用：** internal skills 不参与隐式主路由。", ""]
    return "\n".join(lines)


OUTPUTS = {
    ROOT / "skills" / "README.md": render_skills_readme,
    ROOT / "docs" / "architecture" / "skill-map.md": render_skill_map,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail on drift without rewriting files")
    args = parser.parse_args(argv)
    catalog = load_catalog()
    drift: list[str] = []
    for path, renderer in OUTPUTS.items():
        expected = renderer(catalog)
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                try:
                    label = path.relative_to(ROOT)
                except ValueError:
                    label = path
                drift.append(str(label))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if drift:
        print("generated skill documentation is stale: " + ", ".join(drift), file=sys.stderr)
        return 1
    if not args.check:
        print("rendered: " + ", ".join(str(path.relative_to(ROOT)) for path in OUTPUTS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
